### ISSUE TITLE
Why i cant find m_totalhitsonserver ?

### ISSUE THREAD

**Issue by slhrlx** [JokinAce/CSGO-Offsets#3]
I'm making a hitmarker, but I don't find the offset for m_totalhitsonserver =/

**Comment by JokinAce** [comment]
Because it isn't something HazeDumper gets. Check SpecialOffsets.txt in this repo:
https://github.com/JokinAce/CSGO-Offsets/blob/522f8d975a6a3a329418b1260b1795698c338c03/SpecialOffsets.txt#L915
